import { INestApplication, ValidationPipe } from '@nestjs/common'; import { Test } from '@nestjs/testing'; import request from 'supertest'; import { AppModule } from '../src/app.module';
describe('Phase 7 billing E2E',()=>{let app:INestApplication,admin:string,user:string,business:string,planId:string;beforeAll(async()=>{const m=await Test.createTestingModule({imports:[AppModule]}).compile();app=m.createNestApplication({rawBody:true});app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));await app.init();const login=async(path:string,email:string,password:string)=>(await request(app.getHttpServer()).post(path).send({email,password}).expect(200)).body.tokens.accessToken;admin=await login('/auth/login','admin@reki.app','admin123');user=await login('/auth/login','demo@reki.app','demo1234');business=await login('/auth/business/login','manager@warehouse.com','business123');});afterAll(async()=>{if(planId)await request(app.getHttpServer()).delete(`/admin/subscription-plans/${planId}`).set('authorization',`Bearer ${admin}`);await app.close();});
 it('exposes only the public catalog',async()=>{const r=await request(app.getHttpServer()).get('/subscription-plans').expect(200);expect(Array.isArray(r.body)).toBe(true);expect(r.body.every((p:any)=>p.isActive&&p.isPublic&&!p.stripeProductId)).toBe(true);});
 it('enforces platform-admin authorization',async()=>{await request(app.getHttpServer()).get('/admin/subscription-plans').expect(401);await request(app.getHttpServer()).get('/admin/subscription-plans').set('authorization',`Bearer ${user}`).expect(403);await request(app.getHttpServer()).get('/admin/subscription-plans').set('authorization',`Bearer ${business}`).expect(403);await request(app.getHttpServer()).get('/admin/subscription-plans').set('authorization',`Bearer ${admin}`).expect(200);});
 it('creates, updates and archives a free test plan without Stripe',async()=>{const code=`CI_FREE_${Date.now()}`;const created=await request(app.getHttpServer()).post('/admin/subscription-plans').set('authorization',`Bearer ${admin}`).send({code,name:'CI Free',currency:'GBP',isActive:true,isPublic:true,prices:[{billingInterval:'MONTHLY',amount:0}]}).expect(201);planId=created.body.id;await request(app.getHttpServer()).patch(`/admin/subscription-plans/${planId}`).set('authorization',`Bearer ${admin}`).send({version:created.body.version,name:'CI Free Updated'}).expect(200);await request(app.getHttpServer()).delete(`/admin/subscription-plans/${planId}`).set('authorization',`Bearer ${admin}`).expect(200);planId='';});
 it('rejects invalid webhook signatures',async()=>{await request(app.getHttpServer()).post('/payments/webhooks/stripe').set('stripe-signature','t=1,v1=invalid').set('content-type','application/json').send({id:'evt_fake'}).expect(400);});
 it('serves tenant-scoped current subscription and usage contracts',async()=>{const current=await request(app.getHttpServer()).get('/subscriptions/current').set('authorization',`Bearer ${business}`).expect(200);expect(current.body).toEqual(expect.objectContaining({plan:expect.any(String),effectiveEntitlements:expect.any(Object),usageLimits:expect.any(Object)}));const usage=await request(app.getHttpServer()).get('/billing/usage').set('authorization',`Bearer ${business}`).expect(200);expect(usage.body).toEqual(expect.objectContaining({period:expect.any(Object),usage:expect.any(Array)}));});
 it('protects admin subscription and KPI reporting',async()=>{for(const path of ['/admin/subscriptions','/admin/billing/kpis/payments','/admin/billing/kpis/conversion']){await request(app.getHttpServer()).get(path).expect(401);await request(app.getHttpServer()).get(path).set('authorization',`Bearer ${user}`).expect(403);await request(app.getHttpServer()).get(path).set('authorization',`Bearer ${admin}`).expect(200);}});
});
