import { IsBoolean, IsEnum, IsIn, IsInt, IsNotEmpty, IsOptional, IsString, Matches, Max, Min } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { BillingInterval } from '../entities/billing.entity';

export class InitSubscriptionDto {
  @ApiProperty({ example: 'PRO', description: 'Active database plan code' })
  @Matches(/^[A-Z][A-Z0-9_]{1,63}$/) plan: string;
  @ApiProperty({ enum: BillingInterval })
  @IsEnum(BillingInterval) billingPeriod: BillingInterval;
  @ApiProperty({ description: 'Stable unique key generated by the client for this attempt' })
  @IsString() @IsNotEmpty() idempotencyKey: string;
}
export class ChangeSubscriptionDto { @Matches(/^[A-Z][A-Z0-9_]{1,63}$/) plan:string; @IsEnum(BillingInterval) billingPeriod:BillingInterval; @IsOptional() @IsIn(['IMMEDIATE','NEXT_RENEWAL']) effective?:'IMMEDIATE'|'NEXT_RENEWAL'; @IsString() @IsNotEmpty() idempotencyKey:string; }
export class CancelSubscriptionDto { @IsOptional() @IsBoolean() atPeriodEnd?:boolean; }
export class AdminCancelSubscriptionDto extends CancelSubscriptionDto { @IsOptional() @IsString() reason?:string; }
export class ExtendGraceDto { @IsInt() @Min(1) @Max(90) days:number; @IsOptional() @IsString() reason?:string; }
