import { MigrationInterface, QueryRunner } from 'typeorm';
export class AddPhase71787559500000 implements MigrationInterface {
  async up(q: QueryRunner) {
    await q.query(`CREATE TYPE "phase7_plan" AS ENUM ('FREE','PRO','ENTERPRISE')`);
    await q.query(`CREATE TYPE "phase7_interval" AS ENUM ('MONTHLY','YEARLY')`);
    await q.query(`CREATE TABLE "billing_customers" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL UNIQUE REFERENCES "business_users"("id") ON DELETE CASCADE, "stripeCustomerId" varchar NOT NULL UNIQUE, "createdAt" timestamp NOT NULL DEFAULT now(), "updatedAt" timestamp NOT NULL DEFAULT now())`);
    await q.query(`CREATE TABLE "billing_subscriptions" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL REFERENCES "business_users"("id") ON DELETE CASCADE, "stripeSubscriptionId" varchar UNIQUE, "plan" phase7_plan NOT NULL DEFAULT 'FREE', "status" varchar NOT NULL DEFAULT 'active', "billingInterval" phase7_interval, "stripePriceId" varchar, "startedAt" timestamptz, "currentPeriodStart" timestamptz, "currentPeriodEnd" timestamptz, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "trialEnd" timestamptz, "gracePeriodEnd" timestamptz, "enterpriseOverrides" jsonb, "createdAt" timestamp NOT NULL DEFAULT now(), "updatedAt" timestamp NOT NULL DEFAULT now())`);
    await q.query(`CREATE INDEX "IDX_billing_subscription_business" ON "billing_subscriptions"("businessId")`);
    await q.query(`CREATE TABLE "subscription_events" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "stripeEventId" varchar NOT NULL UNIQUE, "eventType" varchar NOT NULL, "status" varchar NOT NULL DEFAULT 'received', "businessId" uuid, "stripeCustomerId" varchar, "stripeSubscriptionId" varchar, "error" jsonb, "receivedAt" timestamp NOT NULL DEFAULT now(), "processedAt" timestamptz)`);
    await q.query(`CREATE TABLE "usage_ledger" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "userId" uuid, "metric" varchar NOT NULL, "quantity" integer NOT NULL, "source" varchar NOT NULL, "idempotencyKey" varchar NOT NULL, "periodStart" timestamptz NOT NULL, "periodEnd" timestamptz NOT NULL, "metadata" jsonb, "createdAt" timestamp NOT NULL DEFAULT now(), UNIQUE("businessId","metric","idempotencyKey"))`);
    await q.query(`CREATE INDEX "IDX_usage_period" ON "usage_ledger"("businessId","periodStart","periodEnd")`);
    await q.query(`CREATE TABLE "payment_attempts" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "idempotencyKey" varchar NOT NULL, "outcome" varchar NOT NULL, "stripePaymentIntentId" varchar, "metadata" jsonb, "createdAt" timestamp NOT NULL DEFAULT now(), "updatedAt" timestamp NOT NULL DEFAULT now(), UNIQUE("businessId","idempotencyKey"))`);
    await q.query(`CREATE TABLE "interaction_events" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "venueId" uuid, "type" varchar NOT NULL, "idempotencyKey" varchar NOT NULL, "context" jsonb, "createdAt" timestamp NOT NULL DEFAULT now(), UNIQUE("userId","idempotencyKey"))`);
    await q.query(`CREATE INDEX "IDX_interaction_venue_created" ON "interaction_events"("venueId","createdAt")`);
    await q.query(`CREATE TABLE "busyness_observations" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "venueId" uuid NOT NULL, "percentage" integer NOT NULL CHECK ("percentage" BETWEEN 0 AND 100), "level" varchar NOT NULL, "source" varchar NOT NULL DEFAULT 'venue_update', "confidence" double precision NOT NULL DEFAULT 1, "observedAt" timestamptz NOT NULL, "createdAt" timestamp NOT NULL DEFAULT now())`);
    await q.query(`CREATE INDEX "IDX_observation_venue_time" ON "busyness_observations"("venueId","observedAt")`);
    await q.query(`CREATE TABLE "model_versions" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "modelName" varchar NOT NULL, "version" varchar NOT NULL, "status" varchar NOT NULL DEFAULT 'active', "metrics" jsonb, "trainedAt" timestamptz, "deployedAt" timestamp NOT NULL DEFAULT now(), UNIQUE("modelName","version"))`);
  }
  async down(q: QueryRunner) { for (const table of ['model_versions','busyness_observations','interaction_events','payment_attempts','usage_ledger','subscription_events','billing_subscriptions','billing_customers']) await q.query(`DROP TABLE IF EXISTS "${table}" CASCADE`); await q.query(`DROP TYPE IF EXISTS "phase7_interval"`); await q.query(`DROP TYPE IF EXISTS "phase7_plan"`); }
}
