import { MigrationInterface, QueryRunner } from 'typeorm';
export class AddDynamicPlanCatalog1787559600000 implements MigrationInterface {
 async up(q:QueryRunner){
  await q.query(`CREATE TYPE "plan_status" AS ENUM ('DRAFT','ACTIVE','INACTIVE','ARCHIVED')`); await q.query(`CREATE TYPE "stripe_sync_status" AS ENUM ('PENDING','SYNCED','FAILED','OUT_OF_SYNC','NOT_REQUIRED')`); await q.query(`CREATE TYPE "price_change_policy" AS ENUM ('GRANDFATHER','NEXT_RENEWAL')`);
  await q.query(`CREATE TABLE "subscription_plans" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),"code" varchar(64) NOT NULL UNIQUE,"name" varchar(120) NOT NULL,"description" text,"status" plan_status NOT NULL DEFAULT 'DRAFT',"currency" varchar(3) NOT NULL DEFAULT 'GBP',"isPublic" boolean NOT NULL DEFAULT true,"isActive" boolean NOT NULL DEFAULT false,"sortOrder" integer NOT NULL DEFAULT 0,"trialDays" integer NOT NULL DEFAULT 0,"gracePeriodDays" integer NOT NULL DEFAULT 3,"metadata" jsonb,"stripeProductId" varchar,"stripeSyncStatus" stripe_sync_status NOT NULL DEFAULT 'PENDING',"stripeSyncError" text,"stripeSyncedAt" timestamptz,"version" integer NOT NULL DEFAULT 1,"createdAt" timestamp NOT NULL DEFAULT now(),"updatedAt" timestamp NOT NULL DEFAULT now(),"archivedAt" timestamptz)`);
  await q.query(`CREATE TABLE "plan_prices" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),"planId" uuid NOT NULL REFERENCES "subscription_plans"("id") ON DELETE CASCADE,"billingInterval" phase7_interval,"amount" integer NOT NULL CHECK ("amount">=0),"currency" varchar(3) NOT NULL,"stripeProductId" varchar,"stripePriceId" varchar,"active" boolean NOT NULL DEFAULT true,"effectiveFrom" timestamptz NOT NULL DEFAULT now(),"effectiveUntil" timestamptz,"changePolicy" price_change_policy NOT NULL DEFAULT 'GRANDFATHER',"createdAt" timestamp NOT NULL DEFAULT now(),"archivedAt" timestamptz)`); await q.query(`CREATE INDEX "IDX_plan_price_active" ON "plan_prices"("planId","billingInterval","active")`);await q.query(`CREATE UNIQUE INDEX "UQ_plan_price_stripe" ON "plan_prices"("stripePriceId") WHERE "stripePriceId" IS NOT NULL`);await q.query(`CREATE UNIQUE INDEX "UQ_one_active_plan_price" ON "plan_prices"("planId","billingInterval") WHERE "active"=true AND "archivedAt" IS NULL`);
  await q.query(`CREATE TABLE "entitlements" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),"key" varchar(100) NOT NULL UNIQUE,"name" varchar(160) NOT NULL,"description" text,"active" boolean NOT NULL DEFAULT true,"createdAt" timestamp NOT NULL DEFAULT now())`);
  await q.query(`CREATE TABLE "plan_entitlements" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),"planId" uuid NOT NULL REFERENCES "subscription_plans"("id") ON DELETE CASCADE,"entitlementId" uuid NOT NULL REFERENCES "entitlements"("id") ON DELETE CASCADE,"value" jsonb NOT NULL DEFAULT 'true'::jsonb,"createdAt" timestamp NOT NULL DEFAULT now(),UNIQUE("planId","entitlementId"))`);
  await q.query(`CREATE TABLE "plan_usage_limits" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),"planId" uuid NOT NULL REFERENCES "subscription_plans"("id") ON DELETE CASCADE,"metric" varchar(100) NOT NULL,"includedQuantity" bigint,"softLimit" bigint,"hardLimit" bigint,"overageAllowed" boolean NOT NULL DEFAULT false,"overageUnitAmount" bigint,"active" boolean NOT NULL DEFAULT true,"createdAt" timestamp NOT NULL DEFAULT now(),"updatedAt" timestamp NOT NULL DEFAULT now(),UNIQUE("planId","metric"))`);
  await q.query(`ALTER TABLE "billing_subscriptions" ALTER COLUMN "plan" DROP DEFAULT`);await q.query(`ALTER TABLE "billing_subscriptions" ALTER COLUMN "plan" TYPE varchar USING "plan"::text`);await q.query(`ALTER TABLE "billing_subscriptions" ALTER COLUMN "plan" SET DEFAULT 'FREE'`);await q.query(`ALTER TABLE "billing_subscriptions" ADD COLUMN "planId" uuid`);await q.query(`ALTER TABLE "billing_subscriptions" ADD CONSTRAINT "FK_subscription_plan" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE RESTRICT`);await q.query(`CREATE INDEX "IDX_subscription_plan" ON "billing_subscriptions"("planId")`);
  await q.query(`INSERT INTO "entitlements"("key","name") VALUES ('analytics.advanced','Advanced analytics'),('recommendations.smart','Smart recommendations'),('predictions.crowd','Crowd predictions'),('notifications.smart_timing','Smart notification timing'),('offers.promoted','Promoted offers'),('api.extended','Extended API') ON CONFLICT DO NOTHING`);
  await q.query(`INSERT INTO "subscription_plans"("code","name","description","status","isActive","sortOrder","stripeSyncStatus") VALUES ('FREE','Free','Free baseline plan','ACTIVE',true,0,'NOT_REQUIRED'),('PRO','Pro','Professional plan','ACTIVE',true,10,'OUT_OF_SYNC'),('ENTERPRISE','Enterprise','Custom enterprise plan','INACTIVE',false,20,'OUT_OF_SYNC') ON CONFLICT DO NOTHING`);
  await q.query(`UPDATE "billing_subscriptions" s SET "planId"=p.id FROM "subscription_plans" p WHERE p.code=s.plan::text`);
 }
 async down(q:QueryRunner){await q.query(`ALTER TABLE "billing_subscriptions" DROP CONSTRAINT IF EXISTS "FK_subscription_plan"`);await q.query(`ALTER TABLE "billing_subscriptions" DROP COLUMN IF EXISTS "planId"`);for(const t of ['plan_usage_limits','plan_entitlements','entitlements','plan_prices','subscription_plans'])await q.query(`DROP TABLE IF EXISTS "${t}" CASCADE`);await q.query(`DROP TYPE IF EXISTS "price_change_policy"`);await q.query(`DROP TYPE IF EXISTS "stripe_sync_status"`);await q.query(`DROP TYPE IF EXISTS "plan_status"`);}
}
