import { BadGatewayException, BadRequestException, ConflictException, Injectable, Logger, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import Stripe from 'stripe';
import { BusinessUser } from '../business/entities/business-user.entity';
import { BillingCustomer, BillingInterval, BillingSubscription, PaymentAttempt, PlanCode, SubscriptionEvent, UsageLedger } from './entities/billing.entity';
import { EntitlementService } from './entitlement.service';
import { PlanCatalogService } from './plan-catalog.service';
import { ChangeSubscriptionDto } from './dto/billing.dto';
import { ActivityLog } from '../audit/entities/activity-log.entity';

@Injectable()
export class BillingService {
  private readonly logger = new Logger(BillingService.name);
  private readonly stripe?: Stripe;
  constructor(private config: ConfigService, private dataSource: DataSource, private entitlements: EntitlementService, private catalog: PlanCatalogService,
    @InjectRepository(BusinessUser) private businesses: Repository<BusinessUser>,
    @InjectRepository(BillingCustomer) private customers: Repository<BillingCustomer>,
    @InjectRepository(BillingSubscription) private subscriptions: Repository<BillingSubscription>,
    @InjectRepository(SubscriptionEvent) private events: Repository<SubscriptionEvent>,
    @InjectRepository(UsageLedger) private usage: Repository<UsageLedger>,
    @InjectRepository(PaymentAttempt) private attempts: Repository<PaymentAttempt>,
    @InjectRepository(ActivityLog) private audit: Repository<ActivityLog>) {
    const key = this.config.get<string>('billing.stripeSecretKey');
    if (key) this.stripe = new Stripe(key);
  }

  private async businessId(userId: string) {
    const user = await this.businesses.findOne({ where: { id: userId } });
    if (!user) throw new NotFoundException('Business account not found');
    return user.accountOwnerId || user.id;
  }
  private requireStripe() { if (!this.stripe) throw new ServiceUnavailableException('Stripe is not configured'); return this.stripe; }
  private legacyPrice(plan: string, interval: BillingInterval) {
    if (plan === PlanCode.FREE) throw new BadRequestException('FREE does not require payment');
    const id = this.config.get<string>(`billing.prices.${plan.toLowerCase()}.${interval.toLowerCase()}`);
    if (!id) throw new ServiceUnavailableException(`Price is not configured for ${plan}/${interval}`);
    return id;
  }
  async current(userId: string) {
    const businessId = await this.businessId(userId);
    const [sub, customer] = await Promise.all([this.subscriptions.findOne({ where: { businessId }, order: { createdAt: 'DESC' } }), this.customers.findOne({ where: { businessId } })]);
    const effective = sub || this.subscriptions.create({ businessId, plan: PlanCode.FREE, status: 'active' });
    const effectiveEntitlements=await this.entitlements.forSubscription(sub); const stored=sub?.planId?await this.catalog.effectiveValues(sub.planId):null;
    return { ...effective, stripeCustomerId: customer?.stripeCustomerId || null, effectiveEntitlements, usageLimits: stored?.limits||Object.fromEntries(Object.entries(effectiveEntitlements).filter(([k]) => k.startsWith('usage.'))), renewalDate: sub?.currentPeriodEnd || null, trialStatus: sub?.status === 'trialing' };
  }
  async initialize(userId: string, plan: string, interval: BillingInterval, idempotencyKey: string) {
    const stripe = this.requireStripe(); const businessId = await this.businessId(userId); const configured=await this.catalog.activePrice(plan,interval); const price=configured?.price.stripePriceId||this.legacyPrice(plan,interval); const planId=configured?.plan.id;
    const prior = await this.attempts.findOne({ where: { businessId, idempotencyKey } });
    if (prior?.stripePaymentIntentId) throw new ConflictException({ code: 'DUPLICATE_PAYMENT_ATTEMPT', paymentIntentId: prior.stripePaymentIntentId });
    let customer = await this.customers.findOne({ where: { businessId } });
    if (!customer) { const b = await this.businesses.findOneByOrFail({ id: businessId }); const created = await stripe.customers.create({ email: b.email, name: b.name, metadata: { businessId } }, { idempotencyKey: `customer:${businessId}` }); customer = await this.customers.save(this.customers.create({ businessId, stripeCustomerId: created.id })); }
    await this.attempts.upsert({ businessId, idempotencyKey, outcome: 'initiated' }, ['businessId', 'idempotencyKey']);
    const existing = await this.subscriptions.findOne({ where: { businessId }, order: { createdAt: 'DESC' } });
    let subscription: Stripe.Subscription;
    if (existing?.stripeSubscriptionId && ['active', 'trialing', 'past_due'].includes(existing.status)) {
      const remote = await stripe.subscriptions.retrieve(existing.stripeSubscriptionId);
      subscription = await stripe.subscriptions.update(remote.id, { items: [{ id: remote.items.data[0].id, price }], proration_behavior: 'create_prorations' }, { idempotencyKey });
    } else subscription = await stripe.subscriptions.create({ customer: customer.stripeCustomerId, items: [{ price }], payment_behavior: 'default_incomplete', payment_settings: { save_default_payment_method: 'on_subscription' }, expand: ['latest_invoice.confirmation_secret'], metadata: { businessId, plan, planId:planId||'', interval } }, { idempotencyKey });
    const invoice = subscription.latest_invoice as Stripe.Invoice;
    const clientSecret = invoice?.confirmation_secret?.client_secret;
    if (!clientSecret) throw new BadGatewayException('Stripe did not return a payment secret');
    const ephemeral = await stripe.ephemeralKeys.create({ customer: customer.stripeCustomerId }, { apiVersion: '2025-06-30.basil' as any });
    // The confirmation secret belongs to the invoice PaymentIntent. Persist the
    // actual PaymentIntent ID so payment_intent.* webhooks update this attempt.
    const paymentIntentId = clientSecret.split('_secret_')[0];
    await this.attempts.update({ businessId, idempotencyKey }, { stripePaymentIntentId: paymentIntentId, outcome: 'requires_confirmation' });
    return { paymentIntentClientSecret: clientSecret, customerId: customer.stripeCustomerId, ephemeralKey: ephemeral.secret, subscriptionId: subscription.id };
  }
  async portal(userId: string) { const stripe = this.requireStripe(); const businessId = await this.businessId(userId); const c = await this.customers.findOne({ where: { businessId } }); if (!c) throw new NotFoundException('Billing customer not found'); return { url: (await stripe.billingPortal.sessions.create({ customer: c.stripeCustomerId, return_url: this.config.get<string>('billing.portalReturnUrl') })).url }; }
  async changePlan(userId:string,dto:ChangeSubscriptionDto){const stripe=this.requireStripe(),businessId=await this.businessId(userId),target=await this.catalog.activePrice(dto.plan,dto.billingPeriod);if(!target?.price.stripePriceId)throw new BadRequestException('Target plan and interval are not available');const local=await this.subscriptions.findOne({where:{businessId},order:{createdAt:'DESC'}});if(!local?.stripeSubscriptionId)throw new BadRequestException('No active paid subscription');const remote=await stripe.subscriptions.retrieve(local.stripeSubscriptionId);if(!['active','trialing','past_due'].includes(remote.status))throw new ConflictException('Subscription cannot be changed in its current state');const item=remote.items.data[0];if(dto.effective==='NEXT_RENEWAL'){let scheduleId=typeof remote.schedule==='string'?remote.schedule:remote.schedule?.id;if(!scheduleId)scheduleId=(await stripe.subscriptionSchedules.create({from_subscription:remote.id},{idempotencyKey:`schedule:${remote.id}`})).id;const schedule=await stripe.subscriptionSchedules.retrieve(scheduleId);await stripe.subscriptionSchedules.update(scheduleId,{phases:[{items:[{price:item.price.id,quantity:item.quantity||1}],start_date:schedule.phases[0].start_date,end_date:item.current_period_end},{items:[{price:target.price.stripePriceId,quantity:item.quantity||1}],start_date:item.current_period_end}],metadata:{businessId,targetPlanId:target.plan.id,idempotencyKey:dto.idempotencyKey}},{idempotencyKey:`change-next:${remote.id}:${dto.idempotencyKey}`});Object.assign(local,{pendingPlanId:target.plan.id,pendingStripePriceId:target.price.stripePriceId,pendingBillingInterval:dto.billingPeriod,pendingChangeAt:new Date(item.current_period_end*1000)});await this.subscriptions.save(local);return{scheduled:true,effectiveAt:local.pendingChangeAt,subscriptionId:remote.id};}await stripe.subscriptions.update(remote.id,{items:[{id:item.id,price:target.price.stripePriceId}],proration_behavior:'create_prorations',metadata:{...remote.metadata,plan:dto.plan,planId:target.plan.id,interval:dto.billingPeriod}},{idempotencyKey:`change-now:${remote.id}:${dto.idempotencyKey}`});return{pendingWebhook:true,subscriptionId:remote.id};}
  async cancel(userId:string,atPeriodEnd=true){const stripe=this.requireStripe(),businessId=await this.businessId(userId),local=await this.subscriptions.findOne({where:{businessId},order:{createdAt:'DESC'}});if(!local?.stripeSubscriptionId)throw new BadRequestException('No paid subscription');const remote=atPeriodEnd?await stripe.subscriptions.update(local.stripeSubscriptionId,{cancel_at_period_end:true}):await stripe.subscriptions.cancel(local.stripeSubscriptionId);return{subscriptionId:remote.id,status:remote.status,cancelAtPeriodEnd:remote.cancel_at_period_end,pendingWebhook:true};}
  async reactivate(userId:string){const stripe=this.requireStripe(),businessId=await this.businessId(userId),local=await this.subscriptions.findOne({where:{businessId},order:{createdAt:'DESC'}});if(!local?.stripeSubscriptionId)throw new BadRequestException('No paid subscription');const remote=await stripe.subscriptions.retrieve(local.stripeSubscriptionId);if(!remote.cancel_at_period_end) return{subscriptionId:remote.id,status:remote.status,cancelAtPeriodEnd:false,idempotent:true};const updated=await stripe.subscriptions.update(remote.id,{cancel_at_period_end:false});return{subscriptionId:updated.id,status:updated.status,cancelAtPeriodEnd:false,pendingWebhook:true};}
  async adminSubscriptions(q:any){const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||50));const qb=this.subscriptions.createQueryBuilder('s').orderBy('s.createdAt','DESC').skip((page-1)*limit).take(limit);if(q.businessId)qb.andWhere('s.businessId=:businessId',{businessId:q.businessId});if(q.planId)qb.andWhere('s.planId=:planId',{planId:q.planId});if(q.status)qb.andWhere('s.status=:status',{status:q.status});if(q.billingInterval)qb.andWhere('s.billingInterval=:billingInterval',{billingInterval:q.billingInterval});const[items,total]=await qb.getManyAndCount();return{items,total,page,limit};}
  async adminSubscription(id:string){const sub=await this.subscriptions.findOne({where:{id}});if(!sub)throw new NotFoundException('Subscription not found');return sub;}
  async adminCancel(id:string,adminId:string,atPeriodEnd=true,reason?:string){const sub=await this.adminSubscription(id),stripe=this.requireStripe();if(!sub.stripeSubscriptionId)throw new BadRequestException('Subscription has no Stripe subscription');const remote=atPeriodEnd?await stripe.subscriptions.update(sub.stripeSubscriptionId,{cancel_at_period_end:true}):await stripe.subscriptions.cancel(sub.stripeSubscriptionId);await this.adminLog(adminId,'SUBSCRIPTION_ADMIN_CANCELED',sub,{atPeriodEnd,reason});return{subscriptionId:sub.id,status:remote.status,cancelAtPeriodEnd:remote.cancel_at_period_end,pendingWebhook:true};}
  async adminReactivate(id:string,adminId:string){const sub=await this.adminSubscription(id),stripe=this.requireStripe();if(!sub.stripeSubscriptionId)throw new BadRequestException('Subscription has no Stripe subscription');const remote=await stripe.subscriptions.retrieve(sub.stripeSubscriptionId);if(!remote.cancel_at_period_end)return{subscriptionId:id,idempotent:true};await stripe.subscriptions.update(remote.id,{cancel_at_period_end:false});await this.adminLog(adminId,'SUBSCRIPTION_ADMIN_REACTIVATED',sub,{});return{subscriptionId:id,pendingWebhook:true};}
  async adminExtendGrace(id:string,adminId:string,days:number,reason?:string){if(!Number.isInteger(days)||days<1||days>90)throw new BadRequestException('days must be an integer from 1 to 90');const sub=await this.adminSubscription(id),before=sub.gracePeriodEnd;const base=before&&before>new Date()?before:new Date();sub.gracePeriodEnd=new Date(base.getTime()+days*86400000);await this.subscriptions.save(sub);await this.adminLog(adminId,'SUBSCRIPTION_GRACE_EXTENDED',sub,{previous:before,new:sub.gracePeriodEnd,days,reason});return sub;}
  async paymentKpi(from=new Date(Date.now()-30*86400000),to=new Date()){const rows=await this.attempts.createQueryBuilder('p').select('p.outcome','outcome').addSelect('COUNT(*)','count').where('p.createdAt BETWEEN :from AND :to',{from,to}).groupBy('p.outcome').getRawMany();const counts=Object.fromEntries(rows.map(x=>[x.outcome,Number(x.count)]));const eligible=Object.values(counts).reduce((a:number,b:any)=>a+Number(b),0)-(counts.validation_failure||0)-(counts.duplicate||0);return{from,to,counts,eligibleAttempts:eligible,successfulPayments:counts.success||0,successRate:eligible?Number(((counts.success||0)/eligible).toFixed(4)):null};}
  async conversionKpi(from=new Date(Date.now()-90*86400000),to=new Date()){const eligible=await this.businesses.createQueryBuilder('b').where('b.createdAt BETWEEN :from AND :to AND b.isApproved=true AND b.isActive=true',{from,to}).getCount();const paid=await this.subscriptions.createQueryBuilder('s').innerJoin(BusinessUser,'b','b.id=s.businessId').where('b.createdAt BETWEEN :from AND :to',{from,to}).andWhere("s.status IN ('active','trialing') AND s.plan <> 'FREE'").getCount();return{cohortFrom:from,cohortTo:to,eligibleActivatedBusinesses:eligible,paidActiveBusinesses:paid,conversionRate:eligible?Number((paid/eligible).toFixed(4)):null};}
  private adminLog(adminId:string,action:string,sub:BillingSubscription,details:Record<string,unknown>){return this.audit.save(this.audit.create({actorId:adminId,actorRole:'admin',action,target:'billing_subscription',targetId:sub.id,details}));}
  async usageSummary(userId: string) { const businessId = await this.businessId(userId); const current = await this.current(userId); const now = new Date(); const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)); const rows = await this.usage.createQueryBuilder('u').select('u.metric','metric').addSelect('SUM(u.quantity)','used').where('u.businessId = :businessId AND u.periodStart = :start',{ businessId, start }).groupBy('u.metric').getRawMany(); const used = new Map(rows.map(r => [r.metric, Number(r.used)])); const limits = current.usageLimits; return { period: { start, end }, plan: current.plan, usage: Object.entries(limits).map(([metric, quota]) => ({ metric, used: used.get(metric) || 0, includedQuota: quota, remaining: quota === -1 ? null : Math.max(0, Number(quota) - (used.get(metric)||0)), hardLimit: quota, overage: quota === -1 ? 0 : Math.max(0, (used.get(metric)||0)-Number(quota)), units: 'operations' })) }; }
  async recordUsage(businessId: string, metric: string, quantity: number, idempotencyKey: string, source: string) { const now=new Date(); const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)); const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1)); return this.dataSource.transaction(async m => { await m.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${businessId}:${metric}:${start.toISOString()}`]); const duplicate=await m.findOneBy(UsageLedger,{businessId,metric,idempotencyKey});if(duplicate)return duplicate;const sub=await m.findOne(BillingSubscription,{where:{businessId},order:{createdAt:'DESC'}}); const stored=sub?.planId?await this.catalog.effectiveValues(sub.planId):null; const limit=Number(stored?.limits?.[metric] ?? this.entitlements.effective(sub)[metric] ?? 0); const total=Number((await m.createQueryBuilder(UsageLedger,'u').select('COALESCE(SUM(u.quantity),0)','n').where('u.businessId=:businessId AND u.metric=:metric AND u.periodStart=:start',{businessId,metric,start}).getRawOne()).n); if(limit!==-1 && total+quantity>limit) throw new ConflictException({code:'USAGE_LIMIT_EXCEEDED',metric,limit}); return m.save(UsageLedger,m.create(UsageLedger,{businessId,metric,quantity,idempotencyKey,source,periodStart:start,periodEnd:end})); }); }
  constructEvent(raw: Buffer, signature: string) { const secret=this.config.get<string>('billing.stripeWebhookSecret'); if(!secret) throw new ServiceUnavailableException('Stripe webhook secret is not configured'); return this.requireStripe().webhooks.constructEvent(raw, signature, secret); }
  async processEvent(event: Stripe.Event) { if(await this.events.findOne({where:{stripeEventId:event.id,status:'processed'}})) return {received:true,duplicate:true}; const object:any=event.data.object; const customerId=typeof object.customer==='string'?object.customer:object.customer?.id; const customer=customerId?await this.customers.findOne({where:{stripeCustomerId:customerId}}):null; let row=await this.events.findOne({where:{stripeEventId:event.id}}); if(!row) row=await this.events.save(this.events.create({stripeEventId:event.id,eventType:event.type,status:'processing',businessId:customer?.businessId,stripeCustomerId:customerId,stripeSubscriptionId:object.id?.startsWith?.('sub_')?object.id:object.subscription})); try { let stale=false;if(event.type.startsWith('customer.subscription.')) stale=!(await this.syncSubscription(object,customer?.businessId,event.created)); if(event.type==='invoice.paid'||event.type==='payment_intent.succeeded') await this.updateAttempt(object,'success'); if(event.type==='invoice.payment_failed'||event.type==='payment_intent.payment_failed') await this.updateAttempt(object,'declined'); row.status='processed';row.processedAt=new Date();await this.events.save(row);return {received:true,stale}; } catch(error:any){row.status='failed';row.error={message:error.message};await this.events.save(row);throw error;} }
  private async updateAttempt(o:any,outcome:string){const id=o.payment_intent||o.id;if(id) await this.attempts.update({stripePaymentIntentId:id},{outcome});}
  private async syncSubscription(s:any,businessId?:string,eventCreated?:number){businessId=businessId||s.metadata?.businessId;if(!businessId)return true; const price=s.items?.data?.[0]?.price; const configured=price?.id?await this.catalog.priceByStripeId(price.id):null; const plan=(s.metadata?.plan||configured?.plan?.code||this.planFromPrice(price?.id)) as PlanCode; const interval=(s.metadata?.interval||(price?.recurring?.interval==='year'?'YEARLY':'MONTHLY')) as BillingInterval; let local=await this.subscriptions.findOne({where:{stripeSubscriptionId:s.id}});if(local?.lastStripeEventCreated&&eventCreated&&Number(local.lastStripeEventCreated)>eventCreated)return false;if(!local)local=this.subscriptions.create({businessId,stripeSubscriptionId:s.id}); const pendingApplied=local.pendingStripePriceId===price?.id;Object.assign(local,{plan,planId:s.metadata?.planId||configured?.planId||local.planId,status:s.status,billingInterval:interval,stripePriceId:price?.id,startedAt:this.date(s.start_date),currentPeriodStart:this.date(s.items?.data?.[0]?.current_period_start),currentPeriodEnd:this.date(s.items?.data?.[0]?.current_period_end),cancelAtPeriodEnd:s.cancel_at_period_end,trialEnd:this.date(s.trial_end),gracePeriodEnd:s.status==='past_due'?(local.gracePeriodEnd||new Date(Date.now()+Number(this.config.get('billing.graceDays')||3)*86400000)):null,lastStripeEventCreated:eventCreated?String(eventCreated):local.lastStripeEventCreated,...(pendingApplied?{pendingPlanId:null,pendingStripePriceId:null,pendingBillingInterval:null,pendingChangeAt:null}:{})});await this.subscriptions.save(local);return true;}
  private date(v?:number){return v?new Date(v*1000):null;} private planFromPrice(id:string){for(const p of [PlanCode.PRO,PlanCode.ENTERPRISE])for(const i of [BillingInterval.MONTHLY,BillingInterval.YEARLY])if(this.config.get(`billing.prices.${p.toLowerCase()}.${i.toLowerCase()}`)===id)return p;return PlanCode.FREE;}
}
