import { BadRequestException, ConflictException, Injectable, Logger, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, IsNull, Repository } from 'typeorm';
import Stripe from 'stripe';
import { ActivityLog } from '../audit/entities/activity-log.entity';
import { BillingSubscription } from './entities/billing.entity';
import { EntitlementDefinition, PlanEntitlement, PlanPrice, PlanStatus, PlanUsageLimit, PriceChangePolicy, StripeSyncStatus, SubscriptionPlan } from './entities/plan.entity';
import { CreatePlanDto, EntitlementValueDto, PlanPriceDto, UpdatePlanDto, UsageLimitDto } from './dto/plan.dto';

@Injectable()
export class PlanCatalogService {
  private logger=new Logger(PlanCatalogService.name); private stripe?:Stripe;
  constructor(private db:DataSource,config:ConfigService,
    @InjectRepository(SubscriptionPlan) private plans:Repository<SubscriptionPlan>,
    @InjectRepository(PlanPrice) private prices:Repository<PlanPrice>,
    @InjectRepository(EntitlementDefinition) private definitions:Repository<EntitlementDefinition>,
    @InjectRepository(PlanEntitlement) private planEntitlements:Repository<PlanEntitlement>,
    @InjectRepository(PlanUsageLimit) private limits:Repository<PlanUsageLimit>,
    @InjectRepository(BillingSubscription) private subscriptions:Repository<BillingSubscription>,
    @InjectRepository(ActivityLog) private audit:Repository<ActivityLog>) { const key=config.get<string>('billing.stripeSecretKey');if(key)this.stripe=new Stripe(key); }

  async publicCatalog(){const plans=await this.plans.find({where:{isPublic:true,isActive:true,status:PlanStatus.ACTIVE,archivedAt:IsNull()},order:{sortOrder:'ASC',name:'ASC'}});const available=plans.filter(p=>p.stripeSyncStatus===StripeSyncStatus.SYNCED||p.stripeSyncStatus===StripeSyncStatus.NOT_REQUIRED);return Promise.all(available.map(p=>this.view(p,false)));}
  async entitlementDefinitions(){return this.definitions.find({where:{active:true},order:{key:'ASC'}});}
  async all(){const rows=await this.plans.find({order:{sortOrder:'ASC',createdAt:'DESC'}});return Promise.all(rows.map(p=>this.view(p,true)));}
  async one(id:string,admin=true){const p=await this.plans.findOne({where:{id}});if(!p)throw new NotFoundException('Subscription plan not found');return this.view(p,admin);}
  async create(dto:CreatePlanDto,adminId:string){const code=dto.code.toUpperCase();if(await this.plans.exist({where:{code}}))throw new ConflictException('Plan code already exists');this.validatePrices(dto.prices||[]);const plan=await this.db.transaction(async m=>{const p=await m.save(SubscriptionPlan,m.create(SubscriptionPlan,{...dto,code,currency:dto.currency.toUpperCase(),status:dto.isActive?PlanStatus.ACTIVE:PlanStatus.DRAFT,stripeSyncStatus:(dto.prices?.some(x=>x.amount>0)?StripeSyncStatus.PENDING:StripeSyncStatus.NOT_REQUIRED)}));await this.replaceEntitlementsTx(m,p.id,dto.entitlements||[]);await this.replaceLimitsTx(m,p.id,dto.usageLimits||[]);await m.save(ActivityLog,m.create(ActivityLog,{actorId:adminId,actorRole:'admin',action:'PLAN_CREATED',target:'subscription_plan',targetId:p.id,details:{code:p.code,name:p.name}}));return p;});if(dto.prices?.length)await this.syncStripe(plan.id,dto.prices,adminId);return this.one(plan.id);}
  async update(id:string,dto:UpdatePlanDto,adminId:string){const current=await this.plans.findOne({where:{id}});if(!current)throw new NotFoundException('Subscription plan not found');if(dto.code&&dto.code!==current.code&&await this.plans.exist({where:{code:dto.code}}))throw new ConflictException('Plan code already exists');if(dto.version&&dto.version!==current.version)throw new ConflictException('Plan was modified by another administrator');const {prices,entitlements,usageLimits,...changes}=dto;const before={...current};Object.assign(current,changes);if(changes.currency)current.currency=changes.currency.toUpperCase();const saved=await this.plans.save(current);if(entitlements)await this.replaceEntitlements(id,entitlements,adminId);if(usageLimits)await this.replaceUsageLimits(id,usageLimits,adminId);if(prices?.length){this.validatePrices(prices);await this.syncStripe(id,prices,adminId);}await this.log(adminId,'PLAN_UPDATED',id,{previous:this.safePlan(before),next:this.safePlan(saved)});return this.one(id);}
  async setActive(id:string,active:boolean,adminId:string){const p=await this.plans.findOne({where:{id}});if(!p)throw new NotFoundException('Subscription plan not found');p.isActive=active;p.status=active?PlanStatus.ACTIVE:PlanStatus.INACTIVE;await this.plans.save(p);await this.log(adminId,active?'PLAN_ACTIVATED':'PLAN_DEACTIVATED',id,{active});return this.one(id);}
  async archive(id:string,adminId:string){const p=await this.plans.findOne({where:{id}});if(!p)throw new NotFoundException('Subscription plan not found');p.isActive=false;p.isPublic=false;p.status=PlanStatus.ARCHIVED;p.archivedAt=new Date();await this.plans.save(p);await this.prices.update({planId:id,active:true},{active:false,archivedAt:new Date(),effectiveUntil:new Date()});await this.log(adminId,'PLAN_ARCHIVED',id,{});return {archived:true,id};}
  async entitlements(id:string){await this.ensure(id);return this.planEntitlements.find({where:{planId:id},relations:{entitlement:true}});}
  async replaceEntitlements(id:string,values:EntitlementValueDto[],adminId:string){await this.ensure(id);await this.db.transaction(m=>this.replaceEntitlementsTx(m,id,values));await this.log(adminId,'ENTITLEMENTS_UPDATED',id,{keys:values.map(x=>x.key)});return this.entitlements(id);}
  async usageLimits(id:string){await this.ensure(id);return this.limits.find({where:{planId:id,active:true}});}
  async replaceUsageLimits(id:string,values:UsageLimitDto[],adminId:string){await this.ensure(id);this.validateLimits(values);await this.db.transaction(m=>this.replaceLimitsTx(m,id,values));await this.log(adminId,'USAGE_LIMIT_UPDATED',id,{metrics:values.map(x=>x.metric)});return this.usageLimits(id);}
  async subscribers(id:string,page=1,limit=50){await this.ensure(id);const [items,total]=await this.subscriptions.findAndCount({where:{planId:id},order:{createdAt:'DESC'},skip:(page-1)*limit,take:Math.min(limit,100)});return{items,total,page};}
  async usage(id:string){await this.ensure(id);return this.db.createQueryBuilder().select('u.metric','metric').addSelect('SUM(u.quantity)','quantity').from('usage_ledger','u').innerJoin('billing_subscriptions','s','s."businessId"=u."businessId" AND s."planId"=:id',{id}).groupBy('u.metric').getRawMany();}
  async stripeStatus(id:string){const p=await this.plans.findOne({where:{id}});if(!p)throw new NotFoundException('Subscription plan not found');return{planId:id,status:p.stripeSyncStatus,stripeProductId:p.stripeProductId,lastSyncedAt:p.stripeSyncedAt,error:p.stripeSyncError,prices:await this.prices.find({where:{planId:id},order:{createdAt:'DESC'}})};}
  async reconcile(id:string,adminId:string){const p=await this.plans.findOne({where:{id}});if(!p)throw new NotFoundException('Subscription plan not found');const active=await this.prices.find({where:{planId:id,active:true}});return this.syncStripe(id,active.map(x=>({billingInterval:x.billingInterval,amount:x.amount,changePolicy:x.changePolicy})),adminId,true);}
  async activePrice(code:string,interval:string){const plan=await this.plans.findOne({where:{code,isActive:true,status:PlanStatus.ACTIVE,archivedAt:IsNull()}});if(!plan)return null;const price=await this.prices.findOne({where:{planId:plan.id,billingInterval:interval as any,active:true,archivedAt:IsNull()},order:{createdAt:'DESC'}});return price?{plan,price}:null;}
  async priceByStripeId(stripePriceId:string){return this.prices.findOne({where:{stripePriceId},relations:{plan:true}});}
  async effectiveValues(planId:string){const [ents,limits]=await Promise.all([this.entitlements(planId),this.usageLimits(planId)]);return{entitlements:Object.fromEntries(ents.map(x=>[x.entitlement.key,x.value])),limits:Object.fromEntries(limits.map(x=>[x.metric,x.hardLimit===null?-1:Number(x.hardLimit)]))};}
  async syncStripe(id:string,desired:PlanPriceDto[],adminId:string,reconcile=false){const plan=await this.plans.findOne({where:{id}});if(!plan)throw new NotFoundException('Subscription plan not found');if(desired.every(x=>x.amount===0)){plan.stripeSyncStatus=StripeSyncStatus.NOT_REQUIRED;await this.plans.save(plan);await this.persistFreePrices(plan,desired);return this.one(id);}if(!this.stripe)throw new ServiceUnavailableException('Stripe is not configured');plan.stripeSyncStatus=StripeSyncStatus.PENDING;plan.stripeSyncError=null;await this.plans.save(plan);try{if(!plan.stripeProductId){const product=await this.stripe.products.create({name:plan.name,description:plan.description||undefined,metadata:{rekiPlanId:plan.id,code:plan.code}},{idempotencyKey:`reki-plan-product:${plan.id}`});plan.stripeProductId=product.id;await this.plans.save(plan);}for(const d of desired){if(d.amount===0)continue;const existing=await this.prices.findOne({where:{planId:id,billingInterval:d.billingInterval,active:true},order:{createdAt:'DESC'}});if(existing&&existing.amount===d.amount&&existing.stripePriceId)continue;if(existing){existing.active=false;existing.archivedAt=new Date();existing.effectiveUntil=new Date();await this.prices.save(existing);try{await this.stripe.prices.update(existing.stripePriceId,{active:false});}catch(e:any){this.logger.warn(`Could not deactivate Stripe price ${existing.stripePriceId}: ${e.message}`);}}const remote=await this.stripe.prices.create({product:plan.stripeProductId,unit_amount:d.amount,currency:plan.currency.toLowerCase(),recurring:{interval:d.billingInterval==='YEARLY'?'year':'month'},metadata:{rekiPlanId:id,policy:d.changePolicy||PriceChangePolicy.GRANDFATHER}},{idempotencyKey:`reki-price:${id}:${d.billingInterval}:${d.amount}`});await this.prices.save(this.prices.create({planId:id,billingInterval:d.billingInterval,amount:d.amount,currency:plan.currency,stripeProductId:plan.stripeProductId,stripePriceId:remote.id,active:true,changePolicy:d.changePolicy||PriceChangePolicy.GRANDFATHER}));await this.log(adminId,'PRICE_CREATED',id,{interval:d.billingInterval,amount:d.amount,policy:d.changePolicy||PriceChangePolicy.GRANDFATHER});}plan.stripeSyncStatus=StripeSyncStatus.SYNCED;plan.stripeSyncedAt=new Date();plan.stripeSyncError=null;await this.plans.save(plan);return this.stripeStatus(id);}catch(e:any){plan.stripeSyncStatus=StripeSyncStatus.FAILED;plan.stripeSyncError=String(e.message).slice(0,1000);await this.plans.save(plan);this.logger.error(`Plan ${id} Stripe sync failed: ${e.message}`);throw e;}}
  private async persistFreePrices(p:SubscriptionPlan,desired:PlanPriceDto[]){for(const d of desired)if(!await this.prices.exist({where:{planId:p.id,billingInterval:d.billingInterval,active:true}}))await this.prices.save(this.prices.create({planId:p.id,billingInterval:d.billingInterval,amount:0,currency:p.currency,active:true}));}
  private async replaceEntitlementsTx(m:any,id:string,values:EntitlementValueDto[]){await m.delete(PlanEntitlement,{planId:id});for(const v of values){const def=await m.findOne(EntitlementDefinition,{where:{key:v.key,active:true}});if(!def)throw new BadRequestException(`Unknown entitlement: ${v.key}`);await m.save(PlanEntitlement,m.create(PlanEntitlement,{planId:id,entitlementId:def.id,value:v.value}));}}
  private async replaceLimitsTx(m:any,id:string,values:UsageLimitDto[]){this.validateLimits(values);await m.delete(PlanUsageLimit,{planId:id});for(const v of values)await m.save(PlanUsageLimit,m.create(PlanUsageLimit,{planId:id,metric:v.metric,includedQuantity:v.includedQuantity==null?null:String(v.includedQuantity),softLimit:v.softLimit==null?null:String(v.softLimit),hardLimit:v.hardLimit==null?null:String(v.hardLimit),overageAllowed:v.overageAllowed||false,overageUnitAmount:v.overageUnitAmount==null?null:String(v.overageUnitAmount)}));}
  private validatePrices(values:PlanPriceDto[]){if(new Set(values.map(x=>x.billingInterval)).size!==values.length)throw new BadRequestException('Duplicate billing interval');}
  private validateLimits(values:UsageLimitDto[]){if(new Set(values.map(x=>x.metric)).size!==values.length)throw new BadRequestException('Duplicate usage metric');for(const x of values)if(x.hardLimit!==undefined&&x.softLimit!==undefined&&x.hardLimit!==-1&&x.softLimit>x.hardLimit)throw new BadRequestException(`Soft limit exceeds hard limit for ${x.metric}`);}
  private async ensure(id:string){if(!await this.plans.exist({where:{id}}))throw new NotFoundException('Subscription plan not found');}
  private view=async(p:SubscriptionPlan,admin:boolean)=>{const [prices,values]=await Promise.all([this.prices.find({where:{planId:p.id,active:true,archivedAt:IsNull()},order:{billingInterval:'ASC'}}),this.effectiveValues(p.id)]);const base:any={id:p.id,code:p.code,name:p.name,description:p.description,currency:p.currency,isPublic:p.isPublic,isActive:p.isActive,sortOrder:p.sortOrder,trialDays:p.trialDays,gracePeriodDays:p.gracePeriodDays,metadata:p.metadata,prices:prices.map(x=>({id:x.id,billingInterval:x.billingInterval,amount:x.amount,currency:x.currency})),...values};if(admin)Object.assign(base,{status:p.status,version:p.version,stripeSyncStatus:p.stripeSyncStatus,stripeProductId:p.stripeProductId,stripeSyncError:p.stripeSyncError,stripeSyncedAt:p.stripeSyncedAt,archivedAt:p.archivedAt,createdAt:p.createdAt,updatedAt:p.updatedAt});return base;};
  private safePlan(p:SubscriptionPlan){return{code:p.code,name:p.name,status:p.status,currency:p.currency,isPublic:p.isPublic,isActive:p.isActive,trialDays:p.trialDays,gracePeriodDays:p.gracePeriodDays,version:p.version};}
  private log(adminId:string,action:string,id:string,details:Record<string,unknown>){return this.audit.save(this.audit.create({actorId:adminId,actorRole:'admin',action,target:'subscription_plan',targetId:id,details}));}
}
